### ISSUE TITLE
PNG export, missing rsvg-convert

### ISSUE THREAD

**Issue by rbonghi** [nerdyscout/kicad-exports#22]
**Describe the bug**
When selected png format the kicad export fail with a error where is missing `rsvg-convert`
> WARNING:(W017) `rsvg-convert` not installed, using unreliable PNG/JPG conversion (kibot.kibot.out_pcbdraw - log.py:82)
> WARNING:(W018) If you experiment problems install `librsvg2-bin` or equivalent (kibot.kibot.out_pcbdraw - log.py:82)
> ERROR:Failed to run pcbdraw, error 1 (kibot.kibot.out_pcbdraw - out_pcbdraw.py:96)

**To Reproduce**

```yaml
  - name: 'plot images of pcb TOP'
    comment: 'Exports the PCB as a 2D model (SVG, PNG or JPG).'
    type: 'pcbdraw'
    dir: 'docs/img'
    options:
      # [boolean=false] render the bottom side of the board (default is top side)
      bottom: false
      # [number=300] [10,1200] dots per inch (resolution) of the generated image
      dpi: 300
      # [string='svg'] [svg,png,jpg] output format. Only used if no `output` is specified
      format: 'png'
      # [list(string)] list of components to highlight
      # highlight:
      # [list(string)] list of libraries
      libs: ['/usr/share/pcbdraw/footprints/KiCAD-base']
      # [boolean=false] mirror the board
      mirror: false
      # [boolean=false] do not make holes transparent
      no_drillholes: false
      # [string='%f-%i.%x'] name for the generated file . Affected by global options
      output: '%f-Board_%i.%x'
      # [boolean=false] show placeholder for missing components
      placeholder: false
      # [dict|None] replacements for PCB references using components (lib:component)
      remap:
      # [string|list(string)] [none,all] list of components to draw, can be also a string for none or all.
      # The default is none
      show_components: none
      # [string|dict] PCB style (colors). An internal name, the name of a JSON file or the style options
      style: '/usr/share/pcbdraw/styles/jlcpcb-green-hasl.json'
      # [boolean=false] render V-CUTS on the Cmts.User layer
      vcuts: false
      # [string='visible'] [visible,all,none] using visible only the warnings about components in the visible side are generated
      warnings: 'visible'
```
The output in my CI is available here: https://github.com/rnanosaur/nanosaur-exp-board/runs/2012607803?check_suite_focus=true
