### ISSUE TITLE
[BUG] version 2.2 doesn't support "rot_footprint" and 2.3 doesn't run at all

### ISSUE THREAD

**Issue by thejpster** [nerdyscout/kicad-exports#28]
**Describe the bug**
I am using this github action to build my Kicad 5 project. It has been working great, but I had to add a footprint rotation to fix a JLCPCB issue. If I use v2.2, it says 

```
Run nerdyscout/kicad-exports@v2.2
  with:
    config: Kicad/docs.yml
    dir: docs
    schema: Kicad/neotron-pico.sch
    board: Kicad/neotron-pico.kicad_pcb
/usr/bin/docker run --name nerdyscoutkicadexportsv22_b62873 --label 8a33c1 --workdir /github/workspace --rm -e INPUT_CONFIG -e INPUT_DIR -e INPUT_SCHEMA -e INPUT_BOARD -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/Neotron-Pico/Neotron-Pico":"/github/workspace" nerdyscout/kicad-exports:v2.2  "-c Kicad/docs.yml" "-d docs" "-b Kicad/neotron-pico.kicad_pcb" "-e Kicad/neotron-pico.sch"
ERROR:Unknown filter type: `rot_footprint` (kibot.kibot.error - error.py:40)
```

If I upgrade 2.3, it doesn't produce any outputs.

```
Run nerdyscout/kicad-exports@v2.3
  with:
    config: Kicad/docs.yml
    dir: docs
    schema: Kicad/neotron-pico.sch
    board: Kicad/neotron-pico.kicad_pcb
/usr/bin/docker run --name a33c1a0c898db0a2f479dadee8b30b0a17b4e_d4af69 --label 8a33c1 --workdir /github/workspace --rm -e INPUT_CONFIG -e INPUT_DIR -e INPUT_SCHEMA -e INPUT_BOARD -e INPUT_VERBOSE -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/Neotron-Pico/Neotron-Pico":"/github/workspace" 8a33c1:a0c898db0a2f479dadee8b30b0a17b4e  "-c Kicad/docs.yml" "-d docs" "-b Kicad/neotron-pico.kicad_pcb" "-e Kicad/neotron-pico.sch" "-v "
```

**To Reproduce**
- https://github.com/Neotron-Compute/Neotron-Pico, on the "add-test-pads" branch
- the kibot file is "Kicad/docs.yml"

**Expected behavior**

To get PDFs, gerbers, BoM and PnP files.
